"""create planning applications table

Revision ID: 97abb31678a9
Revises: 
Create Date: 2026-08-20 14:00:31.466648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '97abb31678a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('planning_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=False),
    sa.Column('planning_authority', sa.String(), nullable=False),
    sa.Column('application_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('application_status', sa.String(), nullable=True),
    sa.Column('application_type', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('number_residential_units', sa.Integer(), nullable=True),
    sa.Column('floor_area', sa.Float(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planning_authority', 'application_number', name='uq_planning_applications_authority_application_number')
    )
    op.create_geospatial_index('idx_planning_applications_location', 'planning_applications', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_planning_applications_application_number'), 'planning_applications', ['application_number'], unique=False)
    op.create_index(op.f('ix_planning_applications_application_status'), 'planning_applications', ['application_status'], unique=False)
    op.create_index(op.f('ix_planning_applications_decision'), 'planning_applications', ['decision'], unique=False)
    op.create_index(op.f('ix_planning_applications_planning_authority'), 'planning_applications', ['planning_authority'], unique=False)
    op.create_index(op.f('ix_planning_applications_received_date'), 'planning_applications', ['received_date'], unique=False)
    op.create_index(op.f('ix_planning_applications_source_object_id'), 'planning_applications', ['source_object_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_applications_source_object_id'), table_name='planning_applications')
    op.drop_index(op.f('ix_planning_applications_received_date'), table_name='planning_applications')
    op.drop_index(op.f('ix_planning_applications_planning_authority'), table_name='planning_applications')
    op.drop_index(op.f('ix_planning_applications_decision'), table_name='planning_applications')
    op.drop_index(op.f('ix_planning_applications_application_status'), table_name='planning_applications')
    op.drop_index(op.f('ix_planning_applications_application_number'), table_name='planning_applications')
    op.drop_geospatial_index('idx_planning_applications_location', table_name='planning_applications', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('planning_applications')
    # ### end Alembic commands ###
