"""replace planning application composite uniqueness with index

Revision ID: f38e3c079b2d
Revises: 97abb31678a9
Create Date: 2026-08-20 19:44:58.333138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38e3c079b2d'
down_revision: Union[str, Sequence[str], None] = '97abb31678a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_planning_applications_authority_application_number'), 'planning_applications', type_='unique')
    op.create_index('ix_planning_applications_authority_application_number', 'planning_applications', ['planning_authority', 'application_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planning_applications_authority_application_number', table_name='planning_applications')
    op.create_unique_constraint(op.f('uq_planning_applications_authority_application_number'), 'planning_applications', ['planning_authority', 'application_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
