import { useEffect, useRef, type ReactNode } from 'react'

const PLANNING_DATASET_URL =
  'https://data.gov.ie/dataset/national-planning-applications?package_type=dataset'
const CC_BY_LICENSE_URL = 'https://creativecommons.org/licenses/by/4.0/'
const GOOGLE_PRIVACY_URL = 'https://policies.google.com/privacy'
const GOOGLE_MAPS_ADDITIONAL_TERMS_URL =
  'https://maps.google.com/help/terms_maps/'

interface LegalPageProps {
  title: string
  children: ReactNode
}

interface ExternalLinkProps {
  href: string
  children: string
}

function ExternalLink({ href, children }: ExternalLinkProps) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      aria-label={children + ' (opens in a new tab)'}
    >
      {children}
    </a>
  )
}

function LegalPage({ title, children }: LegalPageProps) {
  const headingRef = useRef<HTMLHeadingElement>(null)

  useEffect(() => {
    headingRef.current?.focus()
  }, [])

  return (
    <article className="legal-page" aria-labelledby="legal-page-heading">
      <h2 id="legal-page-heading" ref={headingRef} tabIndex={-1}>
        {title}
      </h2>
      {children}
    </article>
  )
}

export function DataSourcesPage() {
  return (
    <LegalPage title="Data sources">
      <section aria-labelledby="planning-data-heading">
        <h3 id="planning-data-heading">Planning data</h3>
        <p>
          Planning application data is sourced from the Irish Government&apos;s{' '}
          <ExternalLink href={PLANNING_DATASET_URL}>
            National Planning Applications dataset
          </ExternalLink>
          , Irish public-sector planning data published by the Department of
          Housing, Local Government and Heritage.
        </p>
        <p>
          Contains Irish Public Sector Data licensed under a{' '}
          <ExternalLink href={CC_BY_LICENSE_URL}>
            Creative Commons Attribution 4.0 International (CC BY 4.0) licence
          </ExternalLink>
          .
        </p>
      </section>

      <section aria-labelledby="siteforecaster-assessments-heading">
        <h3 id="siteforecaster-assessments-heading">
          SiteForecaster assessments
        </h3>
        <p>
          SiteForecaster processes and augments the source data with its own
          categorisation, electrical-signal analysis and opportunity scoring.
          These assessments are generated by SiteForecaster; they are not part
          of the original government dataset and are not provided or endorsed
          by the Irish Government or individual planning authorities.
        </p>
      </section>

      <section aria-labelledby="data-accuracy-heading">
        <h3 id="data-accuracy-heading">Data accuracy and verification</h3>
        <p>
          Public planning data may be delayed, incomplete or contain errors.
          Verify important information using the official planning application
          linked from SiteForecaster.
        </p>
      </section>
    </LegalPage>
  )
}

export function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy">
      <section aria-labelledby="location-searches-heading">
        <h3 id="location-searches-heading">Location searches</h3>
        <p>
          When you type a location, SiteForecaster sends that query to its
          server for processing with Google Maps Platform Geocoding services.
          Google may process information needed to provide that service in
          accordance with{' '}
          <ExternalLink href={GOOGLE_PRIVACY_URL}>
            Google&apos;s Privacy Policy
          </ExternalLink>
          .
        </p>
      </section>

      <section aria-labelledby="device-location-heading">
        <h3 id="device-location-heading">Device location</h3>
        <p>
          SiteForecaster requests browser or device location only after you
          choose &quot;Use my current location&quot; and your browser grants
          permission. The resulting coordinates are used to search for nearby
          planning opportunities.
        </p>
      </section>

      <section aria-labelledby="location-storage-heading">
        <h3 id="location-storage-heading">
          Location storage and technical information
        </h3>
        <p>
          The current MVP does not intentionally create a user location
          history or profile from typed searches or device coordinates. The
          service temporarily uses IP addresses as in-memory rate-limit
          identifiers. Hosting and other infrastructure providers may also
          process technical request information, such as IP addresses, in
          their normal logs.
        </p>
      </section>

      <section aria-labelledby="accounts-cookies-heading">
        <h3 id="accounts-cookies-heading">Accounts and cookies</h3>
        <p>
          The current MVP does not require user accounts. Its frontend does
          not use analytics, advertising or non-essential cookies, so it does
          not show a cookie banner.
        </p>
      </section>
    </LegalPage>
  )
}

export function TermsPage() {
  return (
    <LegalPage title="Terms of Use">
      <section aria-labelledby="purpose-heading">
        <h3 id="purpose-heading">Purpose</h3>
        <p>
          SiteForecaster is an informational planning-opportunity discovery
          tool for trades and contractors.
        </p>
      </section>

      <section aria-labelledby="planning-information-heading">
        <h3 id="planning-information-heading">Planning information</h3>
        <p>
          Planning information originates from public-sector sources and may
          be incomplete, delayed or inaccurate. Official planning records
          remain the authoritative source.
        </p>
      </section>

      <section aria-labelledby="opportunity-scoring-heading">
        <h3 id="opportunity-scoring-heading">Opportunity scoring</h3>
        <p>
          SiteForecaster&apos;s category, electrical-signal and
          opportunity-score assessments are derived by SiteForecaster. They
          are indicators only and do not guarantee electrical work, contract
          availability, commercial value or project outcome. Independently
          verify information before relying on it for business decisions.
        </p>
      </section>

      <section aria-labelledby="independence-heading">
        <h3 id="independence-heading">Independence</h3>
        <p>
          SiteForecaster is independent. It is not affiliated with, endorsed
          by or operated by the Irish Government, the Department of Housing,
          Local Government and Heritage, individual planning authorities or
          local authorities.
        </p>
      </section>

      <section aria-labelledby="external-links-heading">
        <h3 id="external-links-heading">External links</h3>
        <p>
          SiteForecaster links to third-party planning portals. The
          availability and content of those external services are outside
          SiteForecaster&apos;s control.
        </p>
      </section>

      <section aria-labelledby="google-maps-heading">
        <h3 id="google-maps-heading">Google Maps Platform</h3>
        <p>
          By using SiteForecaster functionality that relies on Google Maps
          Platform, you agree to the{' '}
          <ExternalLink href={GOOGLE_MAPS_ADDITIONAL_TERMS_URL}>
            Google Maps/Google Earth Additional Terms of Service
          </ExternalLink>
          . Google Maps Platform features and content are also subject to{' '}
          <ExternalLink href={GOOGLE_PRIVACY_URL}>
            Google&apos;s Privacy Policy
          </ExternalLink>
          .
        </p>
      </section>
    </LegalPage>
  )
}
